#pragma config(Motor,  port1,           mo_left,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          mo_right,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//change this to match your robot
#define FORWARD	vexRT[Ch1]
#define TURN	vexRT[Ch2]
#define LEFT	motor[mo_left]
#define RIGHT	motor[mo_right]

//Generated with functab.html
int f_tab[128] = {
  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
  0,   0,   0,   0,   0,   1,   1,   1,   1,   1,   1,   1,   1,   2,   2,   2,
  2,   2,   2,   3,   3,   3,   3,   4,   4,   4,   5,   5,   5,   6,   6,   6,
  7,   7,   8,   8,   9,   9,  10,  10,  11,  11,  12,  13,  13,  14,  15,  16,
 16,  17,  18,  19,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  31,
 32,  33,  34,  35,  37,  38,  39,  41,  42,  44,  45,  47,  48,  50,  51,  53,
 55,  57,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  83,  85,
 87,  89,  92,  94,  97,  99, 102, 104, 107, 110, 113, 115, 118, 121, 124, 127,
};

//fixed point approx using function table
//x: [-127, 127]
//ret: [-127, 127]
int func(int *func_tab, int x)
{
	int s = 0;
	if (x < 0) {
		x = -x;
		s = 1;
	}
	if (x > 127)
		x = 127;
	return s ? -func_tab[x] : func_tab[x];
}

//updates function table to a power function
int* changefunc(int *func_tab, float power)
{
	for (int i = 0; i < 128; i++)
		func_tab[i] = round(pow(i / 127.0, power));
	return func_tab;
}

//tries to preserve max speed.
//forward: [-127, 127]
//turn: [-127, 127]
//ret: [-127, 127]
int turn(int forward, int turn)
{
	int max = forward + turn;
	int min = forward - turn;
	if (max > 127)
		return 127;
	if (min > 127)
		return max - (min - 127);
	return max;
}

task main()
{
	while (1) {
		LEFT = turn(func(f_tab, FORWARD), func(f_tab, TURN));
		RIGHT = turn(func(f_tab, FORWARD), -func(f_tab, TURN));
	}
}
